version: "3.3"

services:
  backend:
    build: ./winbook-backend
    image: winbook-backend
    ports:
      - "8081:8081"

    command: python /app/backend/manage.py runserver 0.0.0.0:8081

    volumes:
      - ./winbook-backend:/usr/src/app/

  frontend:
    build : ./winbook-frontend
    image: winbook-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./winbook-frontend:/usr/src/app/
    
    command: npm run start --prod