version: "3.3"

services:
  backend:
    build: ./winbook-backend
    image: winbook-backend
    ports:
      - "8080:8080"

    command: python /app/backend/manage.py runserver 0.0.0.0:8080

    volumes:
      - ./winbook-backend/:/app/backend/

  frontend:
    depends_on:
      - backend
    build : ./winbook-frontend
    image: winbook-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./winbook-frontend/:/usr/src/app/
    
    command: npm run start --prod