version: "3.3"
services:
  web:
    build: .
    image: socialbackend/django
    command: "python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
